package com.acev.api.enums;

public enum RolesEnum {
  AGP_LEADERSHIP,
  AGP_APPRENTICES,
  GD_LEADERSHIP,
  MNT_LEADERSHIP,
  MNT_APPRENTICES,
  SECRETARIAT,
  AGP_LESSONS,
  EBD_TEACHERS,
  PASTORAL_TEAM,
  ADMIN,
  VISITOR,
  LESSONS_READER
}
